const regions = [
  { value: "AP", text: "Andhra Pradesh" },
  { value: "AR", text: "Arunachal Pradesh" },
  { value: "AS", text: "Assam" },
  { value: "BR", text: "Bihar" },
  { value: "CG", text: "Chhattisgarh" },
  { value: "GA", text: "Goa" },
  { value: "GJ", text: "Gujarat" },
  { value: "HR", text: "Haryana" },
  { value: "HP", text: "Himachal Pradesh" },
  { value: "JK", text: "Jammu and Kashmir" },
  { value: "JH", text: "Jharkhand" },
  { value: "KA", text: "Karnataka" },
  { value: "KL", text: "Kerala" },
  { value: "MP", text: "Madhya Pradesh" },
  { value: "MH", text: "Maharashtra" },
  { value: "MN", text: "Manipur" },
  { value: "ML", text: "Meghalaya" },
  { value: "MZ", text: "Mizoram" },
  { value: "NL", text: "Nagaland" },
  { value: "OD", text: "Odisha" },
  { value: "PB", text: "Punjab" },
  { value: "RJ", text: "Rajasthan" },
  { value: "SK", text: "Sikkim" },
  { value: "TN", text: "Tamil Nadu" },
  { value: "TS", text: "Telangana" },
  { value: "TR", text: "Tripura" },
  { value: "UP", text: "Uttar Pradesh" },
  { value: "UK", text: "Uttarakhand" },
  { value: "WB", text: "West Bengal" },
  { value: "AN", text: "Andaman and Nicobar Islands" },
  { value: "CH", text: "Chandigarh" },
  { value: "DN", text: "Dadra and Nagar Haveli and Daman and Diu" },
  { value: "DL", text: "Delhi" },
  { value: "LD", text: "Lakshadweep" },
  { value: "PY", text: "Puducherry" },
];
const transportModes = [
  { value: "road", text: "Road" },
  { value: "air", text: "Air" },
  { value: "fasttrack", text: "FastTrack" },
  { value: "transport", text: "Transport" },
  { value: "train", text: "Train" },
  { value: "local", text: "Local" }
];
